Xhocolatte/Xhocolatte/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),


    path('', include('XhocolatteApp.urls', namespace='xhocolatte')),
    path('blog/', include('XhocolatteBlog.urls', namespace='blog')),
    path('carrito/', include('basket.urls', namespace='basket')),
    path('accounts/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('django.contrib.auth.urls')),
]

Xhocolatte/XhocolatteApp/urls.py
from django.urls import path

from XhocolatteApp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "xhocolatte"

urlpatterns = [
    path('', views.home, name = "Home"),

    path('productos/', views.productos, name = "Productos"),
    path('productos/<slug:slug>', views.detalle_productos, name='detalle_productos'),

    path('politicasPrivacidad/', views.privacidad, name = "Politicas"),
] 

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Xhocolatte/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (UserLoginForm, PwdResetForm, PwdResetConfirmForm)

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    
    # Profile
    path('profile/edit/', views.edit_details, name="edit_details"),
    path('profile/delete_user/', views.delete_user, name="delete_user"),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"), name='delete_confirmation'),
    
    # Password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html", success_url='password_reset_email_confirm', email_template_name='account/password_reset/password_reset_email.html', form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html', success_url='/accounts/password_reset_complete/',  form_class=PwdResetConfirmForm), name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/', TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/', TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),

    # Orders
    path('user_orders/', views.user_orders, name="user_orders"),

    # Addresses
    path('addresses/', views.view_address, name="addresses"),
    path('add_address/', views.add_address, name="add_address"),
    path('addresses/edit/<slug:id>/', views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path('addresses/set_default/<slug:id>/', views.set_default, name="set_default"),

    # WishList
    path('wishlist/add_to_wishlist/<int:id>/', views.add_to_wishlist, name="user_wishlist"),
    path('wishlist', views.wishlist, name="wishlist"),

    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
]

Xhocolatte/basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.resumen_carrito, name='resumen_carrito'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
] 

Xhocolatte/XhocolatteApp/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class ProductType(models.Model):
    name = models.CharField(verbose_name=_("Product Name"), help_text=_("Required"), max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Product Type")
        verbose_name_plural = _("Product Types")

    
    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(verbose_name=_("Name"), help_text=_("Required"), max_length=255)

    class Meta:
        verbose_name = _("Product Specification")
        verbose_name_plural = _("Product Specifications")


    def __str__(self):
        return self.name


class Product(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    title = models.CharField(
        verbose_name=_("Title"), 
        help_text=_("Required"), 
        max_length=255,
    )
    description = models.TextField(verbose_name=_("Description"), help_text=_("Required"), blank=True)
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(
        verbose_name=_("Regular price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99.")
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    discount = models.DecimalField(
        verbose_name=_("Discount price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99.")
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    is_active = models.BooleanField(
        verbose_name=_("Product visibility"),
        help_text=_("Change product visibility"),
        default=True,
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)
    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def get_absolute_url(self):
        return reverse("xhocolatte:detalle_productos", args=[self.slug])

    def __str__(self):
        return self.title


class ProductSpecificationValue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="specification_value")
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(
        verbose_name=_("Value"),
        help_text=_("Product specification value (maximum of 255 words)"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Product Specification Value")
        verbose_name_plural = _("Product Specification Values")


    def __str__(self):
        return self.value


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
    image = models.ImageField(
        verbose_name=_("Image"),
        help_text = _("Upload a product image"),
        upload_to = "images/",
    )
    alt_text = models.CharField(
        verbose_name=_("Alternative text"),
        help_text=_("Please add alternative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")
    

Xhocolatte/XhocolatteApp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login, logout, authenticate
from django.conf import settings
from django.core.mail import send_mail

from XhocolatteApp.models import Product

# Create your views here.

def  home(request):
    return render(request, 'XhocolatteApp/home.html')

def  privacidad(request):
    return render(request, 'XhocolatteApp/politicasPrivacidad.html')

def  productos(request):
    products = Product.objects.all()
    return render(request, 'XhocolatteApp/productos/productos.html', {'products': products})

def detalle_productos(request, slug):
    product = get_object_or_404(Product, slug=slug, is_active=True)
    return render(request, 'XhocolatteApp/productos/detail.html', {'product': product})


    


Xhocolatte/templates/XhocolatteApp/base.html
<html>
  {% load static %}

  <head>
    <title>{% block title %} Xhocolatte {% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/logosinfondo.png' %}" type="image/x-icon"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"/>

    <!-- Styles -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet" />
    <link href="{% static 'css/home.css' %}" rel="stylesheet" />
    <link href="{% static 'css/productos.css' %}" rel="stylesheet" />
    <link href="{% static 'css/basket.css' %}" rel="stylesheet" />
    <link href="{% static 'css/blog.css' %}" rel="stylesheet" />
  </head>

  <body>
<!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
        <div class="container-fluid">
            <div class="d-flex w-100 navbar">
                <a class="navbar-brand d-flex-inline" href="/">
                  <img src="{% static 'img/logosinfondo.png' %}" alt="logo" width="70" height="70" class="rounded-circle">
                </a>
                <ul class="navbar-nav me-auto mb-2 mb-md-0"> 
                  <li class="nav-item">
                    <a class="nav-link d-none d-md-block fw500" style="color:white" href="/" role="button">
                        Inicio 
                    </a>
                  </li>     
                  <li class="nav-item">
                    <a class="nav-link d-none d-md-block fw500" style="color:white" href="/productos" role="button">
                        Productos 
                    </a>
                  </li> 
                  <li class="nav-item">
                    <a class="nav-link d-none d-md-block fw500" style="color:white" href="/blog" role="button">
                        Blog 
                    </a>
                  </li>                    
                </ul>

                <div style="color: white;">
                  <div class="collapse navbar-collapse" id="navbarSupportedContent2">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-reset" href="#" id="navbarDropdown" role="button"
                          data-bs-toggle="dropdown" aria-expanded="false">
                          <div class="small" style="color: white;">
                            {% if user.is_authenticated %}
                              {{ request.user.name }}
                            {% else %}
                            Login
                            {% endif %}
                          </div>
                          <span class="fs15 fw500">Opciones de Cuenta
                          </span>
                          </span>
                        </a>
                        <div class="dropdown-menu rounded-0" aria-labelledby="navbarDropdown">
                          <div class="card border-0">
                            <div class="card-body">
                              <h6 class="card-title">Cuenta</h6>
                              <ul class="list-group list-group-flush dropdown-account-link">
                                {% if user.is_authenticated %}
                                <a href="{% url "account:dashboard" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Su Cuenta</a>
                                <a href="{% url "account:user_orders" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Pedidos</a>
                                <a href="{% url "account:logout" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Logout</a>      
                                {% else %}
                                <a href="{% url "account:dashboard" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Login</a>
                                {% endif %}
                              </ul>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>

                <a type="button" role="button" href="{% url 'basket:resumen_carrito' %}"
                    class="btn btn-outline-secondary border-0 basket-btn">

                    {% with total_qty=basket|length %}
                    <div id="basket-qty" class="basket-qty" style="color: white;">
                        {% if total_qty > 0 %}
                          {{ total_qty }}
                        {% else %}
                          0
                        {% endif %}
                    </div>
                    {% endwith %}
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="white"
                            class="bi bi-cart3" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                    </div>
                    <span class="fs15 fw500" style="color:white">Carrito</span>
                </a>
            </div>
        </div>
    </nav>
    
    <!-- Heading -->
    {% block content %} {% endblock %}

    <!-- Footer -->
    <footer class="footer">
      <div class="contenedor-footer">
        <div class="contenedor-footer-contenido">
          <h3 class="website-logo">Xhocolatte</h3>
          <a href="tel:+34111111111" class="footer-info">111-111-111</a>
          <a href="mailto:xhocolatte@gmail.com" class="footer-info">xhocolatte@gmail.com</a>
        </div>

        <div class="footer-menus">
          <div class="contenedor-footer-contenido">
            <span class="titulo-menu">Menú</span>
            <a href="/" class="menu-item-footer">Home</a>
            <a href="/productos" class="menu-item-footer">Productos</a>
            <a href="/blog" class="menu-item-footer">Blog</a>
            <a href="/contacto" class="menu-item-footer">Contacto</a>
            <a href="{% url "account:dashboard" %}" class="menu-item-footer">Login</a>
          </div>

          <div class="contenedor-footer-contenido">
            <span class="titulo-menu">Legal</span>
            <a href="/politicasPrivacidad" class="menu-item-footer">Política de Privacidad</a>
            <a href="/politicasPrivacidad" class="menu-item-footer">Cookies</a>
            <a href="/politicasPrivacidad" class="menu-item-footer">Términos y Condiciones</a>
          </div>
        </div>

        <div class="contenedor-footer-contenido">
          <span class="titulo-menu">Follow Us</span>

          <div class="contenedor-social" >
            <a href="" class="links-sociales"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
              <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
            </svg>
          </a>
            <a href="" class="links-sociales" style="color: white;">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
              </svg>
            </a>
            <a href="" class="links-sociales" style="color: white;">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
              </svg>
            </a>
          </div>
        </div>
      </div>

      <div class="contenedor-copyright">
        <span class="copyright">&copy; 2022, Xhocolatte</span>
      </div>
    </footer>

  </body>
</html>

Xhocolatte/templates/XhocolatteApp/blog.html
{% extends "./base.html" %}

{% load static %}

{% block title %} Blog {% endblock %}

{% block content %}

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<section class="blog" style="padding-bottom: 500px; padding-top: 100px;">
    <div class="cabecera-blog">
        <h3>Nuestros Últimos Posts:</h3>
    </div>

    {% for blog in blogs %}
        <!--Blog 1-->
        <div class="contenedor-blog">
            <div class="box-blog">
                <div class="img-blog">
                    <a href=""><img src="{{ blog.image.url }}" alt="Blog"></a>
                </div>

                <div class="texto-blog">
                    
                    <span>{{blog.created_at}} / {{blog.title}}</span>
                    
                    <a href="/" class="titulo-blog">Las mejores calidades, los mejores artesanos.</a>
                    <p>{{blog.content|safe}}</p>
                    <a href="/productos">¿Quieres probar?</a>
                </div>
            </div>
        </div>
    
    {% endfor %}
</section>
{% endblock %}

Xhocolatte/templates/XhocolatteApp/contactoExitoso.html
{% extends "./base.html" %}

{% block title %} Contacto {% endblock %}

{% block content %}



<h1>Correo enviado correctamente</h1>



{% endblock %}

Xhocolatte/templates/XhocolatteApp/politicasPrivacidad.html
<p><strong>POLÍTICA DE PRIVACIDAD</strong></p>
<p>
  El presente Política de Privacidad establece los términos en que Xhocolatte
  usa y protege la información que es proporcionada por sus usuarios al momento
  de utilizar su sitio web. Esta compañía está comprometida con la seguridad de
  los datos de sus usuarios. Cuando le pedimos llenar los campos de información
  personal con la cual usted pueda ser identificado, lo hacemos asegurando que
  sólo se empleará de acuerdo con los términos de este documento. Sin embargo
  esta Política de Privacidad puede cambiar con el tiempo o ser actualizada por
  lo que le recomendamos y enfatizamos revisar continuamente esta página para
  asegurarse que está de acuerdo con dichos cambios.
</p>
<p><strong>Información que es recogida</strong></p>
<p>
  Nuestro sitio web podrá recoger información personal por ejemplo:
  Nombre,&nbsp; información de contacto como&nbsp; su dirección de correo
  electrónica e información demográfica. Así mismo cuando sea necesario podrá
  ser requerida información específica para procesar algún pedido o realizar una
  entrega o facturación.
</p>
<p><strong>Uso de la información recogida</strong></p>
<p>
  Nuestro sitio web emplea la información con el fin de proporcionar el mejor
  servicio posible, particularmente para mantener un registro de usuarios, de
  pedidos en caso que aplique, y mejorar nuestros productos y servicios.
  &nbsp;Es posible que sean enviados correos electrónicos periódicamente a
  través de nuestro sitio con ofertas especiales, nuevos productos y otra
  información publicitaria que consideremos relevante para usted o que pueda
  brindarle algún beneficio, estos correos electrónicos serán enviados a la
  dirección que usted proporcione y podrán ser cancelados en cualquier momento.
</p>
<p>
  Xhocolatte está altamente comprometido para cumplir con el compromiso de
  mantener su información segura. Usamos los sistemas más avanzados y los
  actualizamos constantemente para asegurarnos que no exista ningún acceso no
  autorizado.
</p>
<p><strong>Cookies</strong></p>
<p>
  Una cookie se refiere a un fichero que es enviado con la finalidad de
  solicitar permiso para almacenarse en su ordenador, al aceptar dicho fichero
  se crea y la cookie sirve entonces para tener información respecto al tráfico
  web, y también facilita las futuras visitas a una web recurrente. Otra función
  que tienen las cookies es que con ellas las web pueden reconocerte
  individualmente y por tanto brindarte el mejor servicio personalizado de su
  web.
</p>
<p>
  Nuestro sitio web emplea las cookies para poder identificar las páginas que
  son visitadas y su frecuencia. Esta información es empleada únicamente para
  análisis estadístico y después la información se elimina de forma permanente.
  Usted puede eliminar las cookies en cualquier momento desde su ordenador. Sin
  embargo las cookies ayudan a proporcionar un mejor servicio de los sitios web,
  estás no dan acceso a información de su ordenador ni de usted, a menos de que
  usted así lo quiera y la proporcione directamente
  <a href="" target="_blank"></a>. Usted puede aceptar o negar el uso de
  cookies, sin embargo la mayoría de navegadores aceptan cookies automáticamente
  pues sirve para tener un mejor servicio web. También usted puede cambiar la
  configuración de su ordenador para declinar las cookies. Si se declinan es
  posible que no pueda utilizar algunos de nuestros servicios.
</p>
<p><strong>Enlaces a Terceros</strong></p>

<p><strong>Control de su información personal</strong></p>
<p>
  En cualquier momento usted puede restringir la recopilación o el uso de la
  información personal que es proporcionada a nuestro sitio web.&nbsp; Cada vez
  que se le solicite rellenar un formulario, como el de alta de usuario, puede
  marcar o desmarcar la opción de recibir información por correo electrónico.
  &nbsp;En caso de que haya marcado la opción de recibir nuestro boletín o
  publicidad usted puede cancelarla en cualquier momento.
</p>
<p>
  Esta compañía no venderá, cederá ni distribuirá la información personal que es
  recopilada sin su consentimiento, salvo que sea requerido por un juez con un
  orden judicial.
</p>
<p>
  Xhocolatte Se reserva el derecho de cambiar los términos de la presente
  Política de Privacidad en cualquier momento.
</p>


Xhocolatte/templates/XhocolatteApp/sub_base.html
{% extends "./base.html" %}
{% load static %}
{% block stylesheet %}{% static 'account/css/account.css' %}{% endblock %}

{% block content %}
<div class="container">
  <div class="login d-flex align-items-center">
    <div class="col-12 col-md-12 col-lg-12 mx-auto">
      {% block sub_content %}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}