Xhocolatte/Xhocolatte/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),


    path('', include('XhocolatteApp.urls', namespace='xhocolatte')),
    path('blog/', include('XhocolatteBlog.urls', namespace='blog')),
    path('carrito/', include('basket.urls', namespace='basket')),
    path('accounts/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('django.contrib.auth.urls')),
]

Xhocolatte/XhocolatteApp/urls.py
from django.urls import path

from XhocolatteApp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "xhocolatte"

urlpatterns = [
    path('', views.home, name = "Home"),

    path('productos/', views.productos, name = "Productos"),
    path('productos/<slug:slug>', views.detalle_productos, name='detalle_productos'),

    path('politicasPrivacidad/', views.privacidad, name = "Politicas"),
] 

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Xhocolatte/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (UserLoginForm, PwdResetForm, PwdResetConfirmForm)

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    
    # Profile
    path('profile/edit/', views.edit_details, name="edit_details"),
    path('profile/delete_user/', views.delete_user, name="delete_user"),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"), name='delete_confirmation'),
    
    # Password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html", success_url='password_reset_email_confirm', email_template_name='account/password_reset/password_reset_email.html', form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html', success_url='/accounts/password_reset_complete/',  form_class=PwdResetConfirmForm), name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/', TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/', TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),

    # Orders
    path('user_orders/', views.user_orders, name="user_orders"),

    # Addresses
    path('addresses/', views.view_address, name="addresses"),
    path('add_address/', views.add_address, name="add_address"),
    path('addresses/edit/<slug:id>/', views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path('addresses/set_default/<slug:id>/', views.set_default, name="set_default"),

    # WishList
    path('wishlist/add_to_wishlist/<int:id>/', views.add_to_wishlist, name="user_wishlist"),
    path('wishlist', views.wishlist, name="wishlist"),

    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
]

Xhocolatte/basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.resumen_carrito, name='resumen_carrito'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
] 

Xhocolatte/XhocolatteApp/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class ProductType(models.Model):
    name = models.CharField(verbose_name=_("Product Name"), help_text=_("Required"), max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Product Type")
        verbose_name_plural = _("Product Types")

    
    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(verbose_name=_("Name"), help_text=_("Required"), max_length=255)

    class Meta:
        verbose_name = _("Product Specification")
        verbose_name_plural = _("Product Specifications")


    def __str__(self):
        return self.name


class Product(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    title = models.CharField(
        verbose_name=_("Title"), 
        help_text=_("Required"), 
        max_length=255,
    )
    description = models.TextField(verbose_name=_("Description"), help_text=_("Required"), blank=True)
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(
        verbose_name=_("Regular price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99.")
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    discount = models.DecimalField(
        verbose_name=_("Discount price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99.")
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    is_active = models.BooleanField(
        verbose_name=_("Product visibility"),
        help_text=_("Change product visibility"),
        default=True,
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)
    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def get_absolute_url(self):
        return reverse("xhocolatte:detalle_productos", args=[self.slug])

    def __str__(self):
        return self.title


class ProductSpecificationValue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="specification_value")
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(
        verbose_name=_("Value"),
        help_text=_("Product specification value (maximum of 255 words)"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Product Specification Value")
        verbose_name_plural = _("Product Specification Values")


    def __str__(self):
        return self.value


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
    image = models.ImageField(
        verbose_name=_("Image"),
        help_text = _("Upload a product image"),
        upload_to = "images/",
    )
    alt_text = models.CharField(
        verbose_name=_("Alternative text"),
        help_text=_("Please add alternative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")
    

Xhocolatte/XhocolatteApp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login, logout, authenticate
from django.conf import settings
from django.core.mail import send_mail

from XhocolatteApp.models import Product

# Create your views here.

def  home(request):
    return render(request, 'XhocolatteApp/home.html')

def  privacidad(request):
    return render(request, 'XhocolatteApp/politicasPrivacidad.html')

def  productos(request):
    products = Product.objects.all()
    return render(request, 'XhocolatteApp/productos/productos.html', {'products': products})

def detalle_productos(request, slug):
    product = get_object_or_404(Product, slug=slug, is_active=True)
    return render(request, 'XhocolatteApp/productos/detail.html', {'product': product})


    


Xhocolatte/templates/XhocolatteApp/productos/detail.html
{% extends "../base.html" %}

{% block title %} {{ producto.nombre }} {% endblock %}

{% block content %}

    <div class="container">
        {% if messages %}
            <div style="margin-top: 50px;" class="alert alert-warning" alert-{{ message.tags }}" role="alert">
        {% for message in messages  %}
            {{message|safe}} - <a href="{% url "account:wishlist" %}" class="alert-link">Sus Favoritos</a>.
        {% endfor %}
            </div>
        {% endif %}
        <div class="row g-3 mb-5 mt-5">
            <div class="col-md-5  col-lg-5 order-md-first bg-light">
                {% for image in product.product_image.all %}
                    {% if image.is_feature %}
                <img src="{{ image.image.url }}" alt="{{ image.image.alt_text }}" alt="Imagen Responsive" class="img-fluid mx-auto d-block">
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col-md7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-3 h4">{{ product.title }}</h1>

                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Precio: </div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">{{ product.regular_price }}€</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select" class="me-2">Cantidad</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>
                            </div>
                            <div class="col-6 text-end">
                                <button type="button" id="add-button" value="{{ product.id }}" class="btn btn-success btn-sm">Añadir al Carrito</button>
                                <a href="{% url 'account:user_wishlist' product.id  %}" class="btn btn-light fw500" role="button" aria-disabled="true">Añadir a lista de Favoritos</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        
        $(document).on('click', '#add-button', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_add" %}',
                data: {
                    productid: $('#add-button').val(),
                    productqty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function(json){
                    document.getElementById('basket-qty').innerHTML = json.qty;
                },
                error: function(xhr, errmsg, err){}
            });
        });

    </script>

{% endblock %}

Xhocolatte/templates/XhocolatteApp/productos/productos.html
{% extends "../base.html" %}

{% block title %} Productos {% endblock %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">

        <div class="cabecera-blog" style="padding-bottom: 40px; padding-top: 40px;">
            <h3>Nuestros Últimos Productos:</h3>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" style="padding-bottom: 500px;">

        {% if not products %}
            <div class="col-12">Todavía no hay productos</div>
        {% else %}

            {% for product in products %}

                <div class="col">
                    <div class="card shadow-sm">

                        {% for image in product.product_image.all %}
                            {% if image.is_feature %}
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ image.image.url }}" alt="{{ image.image.alt_text }}" alt="Imagen Responsive" class="img-fluid"/>
                                </a>
                            {% endif %}
                        {% endfor %}

                        <div class="card-body">
                            <p class="card-text">
                                <a href="{{ product.get_absolute_url }}" class="text-dark text-decoration-none h5">{{ product.title }}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{ product.description }}</small>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}

        </div>

        {% endif %}
    </div>
</div>

{% endblock %}