Xhocolatte/Xhocolatte/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),


    path('', include('XhocolatteApp.urls', namespace='xhocolatte')),
    path('blog/', include('XhocolatteBlog.urls', namespace='blog')),
    path('carrito/', include('basket.urls', namespace='basket')),
    path('accounts/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('django.contrib.auth.urls')),
]

Xhocolatte/basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.resumen_carrito, name='resumen_carrito'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
] 

Xhocolatte/checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'

urlpatterns = [
    path("deliverychoices", views.deliverychoices, name="deliverychoices"),
    path("basket_update_delivery/", views.basket_update_delivery, name="basket_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

Xhocolatte/templates/carrito/resumen.html
{% extends '../XhocolatteApp/base.html' %}
{% load static %}

{% block title %}Resumen Carrito{% endblock %}

{% block content %} 

<main class="pt-5" style="padding-bottom: 500px;">
    <div class="container" style="max-width: 1000px">
      <div class="">
        <h2 class="titulo-html" style="padding-top: 50px;">Tu Carrito</h2>
      </div>
      <div class="col-12">
        <p>Maneja tus <b>productos</b> en el carrito</p>
      </div>
      <hr />
    </div>
    <div class="container" style="max-width: 1000px">
      
      <div class="row g-3">
        <div class="col-12 bg-light p-3 d-flex justify-content-between">
          <div class="d-flex d-flex-inline">
            <div class="pe-3">Pedido</div>
            <div class="dropdown">
            <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink" data-bs-toggle="dropdown" aria-expanded="false">
            Opciones de compra
            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
            </svg>
            </a>
  
            <ul class="dropdown-menu" aria-labelledby="dropdownLink">
              <li class="item small">Entrega día siguiente</li>
              <li class="item small">Entrega Premium</li>
            </ul>
            </div>
          </div>
          <div class="text-end">
            
            <div class="pt-2">Total a pagar: <span id="total" class="fw-bold h5">{{basket.get_subtotal_price}}</span><span class="fw-bold h5">€</span></div>
            
          </div>
        </div>
        <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
          <div class="d-grid gap-2 ">
            <a role="button" href="{% url 'checkout:deliverychoices' %}" class="btn btn-success fw-bold" type="button">Pago Seguro</a>
            <button class="btn btn-secondary" type="button">Guardar para más tarde</button>
          </div>
        </div>
        <div class="col-md-7 col-lg-8 p-0">
  
          {% for item in basket %} 
          {% with product=item.product %}
  
          <div class="card mb-3 border-0 product-item" data-index="{{product.id}}" style="padding-bottom: 20px;">
            <div class="row g-0">
              <div class="col-md-2 d-none d-md-block">
                {% for image in product.product_image.all %}
                  {% if image.is_feature %}
                    <img class="img-fluid mx-auto d-block" alt="{{ image.image.alt_text }}" alt="Responsive image" src="{{ image.image.url }}" />
                  {% endif %}
                {% endfor %}
              </div>
              <div class="col-md-10 ps-md-3">
                <div class="card-body p-1">
                  <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                    <p class="card-text pb-3">{{product.title}}</p>
                  </a>
                      <label for="select" class="me-2">Cantidad</label>
                      <select id="select{{product.id}}" style="width:50px;height:31px;">
                        <option value="" selected disabled hidden>{{item.qty}}</option>
                        <option value="">1</option>
                        <option value="">2</option>
                        <option value="">3</option>
                        <option value="">4</option>
                      </select>
                  <a type="button" id="update-button" data-index="{{product.id}}" class="update-button text-decoration-none small ps-3">Actualizar &nbsp;&nbsp;</a>
                  |
                  <a type="button" id="delete-button" data-index="{{product.id}}" class="delete-button text-decoration-none small ps-3">Eliminar</a>
                </div>
              </div>
            </div>
          </div>
          {% endwith %} 
          {% endfor %}
        </div>
      </div>
      
    </div>
  </main>
  


  <script>
    // Delete Item
    $(document).on("click", ".delete-button", function (e) {
      e.preventDefault();
      var prodid = $(this).data("index");
      $.ajax({
        type: "POST",
        url: '{% url "basket:basket_delete" %}',
        data: {
          productid: $(this).data("index"),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: "post",
        },
        success: function (json) {
          $('.product-item[data-index="' + prodid + '"]').remove();
  
          document.getElementById("basket-qty").innerHTML = json.qty;
          document.getElementById("total").innerHTML = json.subtotal;
        },
        error: function (xhr, errmsg, err) {},
      });
    });
  
    // Update Item
    $(document).on("click", ".update-button", function (e) {
      e.preventDefault();
      var prodid = $(this).data("index");
      $.ajax({
        type: "POST",
        url: '{% url "basket:basket_update" %}',
        data: {
          productid: $(this).data("index"),
          productqty: $("#select" + prodid + " option:selected").text(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: "post",
        },
        success: function (json) {
            
          document.getElementById("basket-qty").innerHTML = json.qty;
          document.getElementById("total").innerHTML = json.subtotal;
        },
        error: function (xhr, errmsg, err) {},
      });
    });
  </script>

{% endblock %}